### ISSUE TITLE
sketch all non-overlapping genes on one track

### ISSUE THREAD

**Issue by paristzou** [genometools/genometools#1023]
## Problem description
I want to sketch all non-overlapping genes on one track. But it generates genes on three tracks.

## Exact command line call triggering the problem
gt sketch -format png output.png NC0130412.gff3

```
gt ...
```

##  NC0130412.gff3
##gff-version   3
##sequence-region foo 1 120000
foo     gth1    bibi    1       3579    .       +       .       ID=orf1
foo     gth1    bibi    4423    27223   .       +       .       ID=orf2
foo     gth1    bibi    28503   29811   .       +       .       ID=orf3
foo     gth1    bibi    30062   30427   .       +       .       ID=orf4
foo     gth1    bibi    30668   31633   .       -       .       ID=orf5
foo     gth1    bibi    109381  109980  .       +       .       ID=orf6
foo     gth1    bibi    110488  111174  .       +       .       ID=orf7
foo     gth1    bibi    111576  112682  .       +       .       ID=orf8
foo     gth1    bibi    112767  113663  .       -       .       ID=orf9

## What GenomeTools version are you reporting an issue for (as output by `gt -version`)? 
gt (GenomeTools) 1.6.2

## Did you compile GenomeTools from source? If so, please state the `make` parameters used.
apt-get install genometools (https://github.com/genometools/genometools)

## What operating system (e.g. Ubuntu, Mac OS X), OS version (e.g. 15.10, 10.11) and platform (e.g. x86_64) are you using?

Distributor ID: Ubuntu
Description:    Ubuntu 20.04.5 LTS
Release:        20.04
Codename:       focal

**Comment by satta** [comment]
When running your command line and input, I get an output in which all features are in one track, the `NC0130412.gff3|bibi` track:
![output](https://github.com/genometools/genometools/assets/27732/6dfc9782-7b33-41ed-8536-a44877caabda)

Are you referring to the fact that the features are distributed across three lines? This is the case because the descriptions would overlap each other if drawn within one line, so the feature blocks are pushed to a new line to avoid overlaps in such crowded locations.
If you don't want that, you need to disable the `split_lines` option for the type in question, e.g. like in this `no-split-lines.style` style file:
```lua
style =
{
  bibi = {
    split_lines        = false,
  },
  format = {
    -- Set the following three settings to 'false' to globally disable them.
    show_block_captions = true, -- generally show captions
    show_track_captions = true, -- generally show track captions
    margins = 30,      -- space left and right of diagram, in pixels
    bar_height = 16,   -- height of a feature bar, in pixels
    bar_vspace = 10,   -- space between feature bars, in pixels
    track_vspace = 15, -- space between tracks, in pixels
    ruler_font_size = 8, -- size of scale labels
    ruler_space = 20, -- space between ruler and first track
    block_caption_font_size = 8, -- size of block captions
    track_caption_font_size = 8, -- size of track captions
    track_caption_space = 7, -- space between tracks and their captions
    scale_arrow_width = 6,     -- width of scale arrowheads, in pixels
    scale_arrow_height = 10,   -- height of scale arrowheads, in pixels
    arrow_width = 6,   -- width of feature arrowheads, in pixels
    stroke_width = .5, -- width of outlines, in pixels
    unit = "bp",       -- basepair unit, e.g. "bp"
    ruler_left_text = "5'",  -- text left of the ruler axis
    ruler_right_text = "3'", -- text right of the ruler axis
    stroke_marked_width = 1.5, -- width of outlines for marked elements, in pixels
    show_grid = true, -- shows light vertical lines for orientation
    min_len_block = 20 , -- minimum length of a block in which single elements are shown
    track_title_color     = {red=0.7, green=0.7, blue=0.7, alpha = 1.0},
    default_stroke_color  = {red=0.1, green=0.1, blue=0.1, alpha = 1.0},
    background_color      = {red=1.0, green=1.0, blue=1.0, alpha = 1.0},
  },
}
```
and running
```
gt sketch -style no-split-lines.style -format png output.png NC0130412.gff3
```
which results in:
![output](https://github.com/genometools/genometools/assets/27732/a42d9bc9-ccfc-4add-962e-c1a47f57111a)

**Comment by paristzou** [comment]
Thank you so much. One question: if I want to color each gene differently, using of bibi_red, bibi_blue (by adding fill= {red=1.0, green=0.0, blue=0.0} to each bibi) push each gene to different tracks again.
###
bibi_blue = {
    split_lines        = false,
    fill               = {red=0.0, green=0.0, blue=1.0},
},

bibi_red  = {
    split_lines        = false,
    fill               = {red=1.0, green=0.0, blue=0.0},
},
###
Thank you for your time,

**Comment by satta** [comment]
They are shown in different tracks because if you modify your GFF3 like that, you have different types for the features, and AnnotationSketch uses the feature types to determine what track to show a feature in.

A better way would be to do keep the annotation the same and just change the color assignment in your style file:
```lua
  bibi = {
    split_lines        = false,
    fill               = function(gn)
                            id = gn:get_attribute("ID")
                            if id == "orf2" then
                                return {red=0.0, green=0.0, blue=1.0}
                            else
                                return {red=1.0, green=0.0, blue=0.0}
                            end
                        end,
  },
```
which would generate this:
![output](https://github.com/genometools/genometools/assets/27732/0214e1cc-45e5-4541-aa3f-dc324bf0075e)

The annotation (GFF3) is assumed to be always fixed; it is advised to change the style file only. You can assign functions to keys like "fill" to dynamically determine the value. The function gets called for each feature of the given type. This allows, for example, to style  features in alternating red and blue fill colors:
```lua
  bibi = {
    split_lines        = false,
    fill               = function(gn)
                            if red then
                              red = false
                            else 
                              red = true
                            end
                            if red then
                                return {red=1.0, green=0.0, blue=0.0}
                            else
                                return {red=0.0, green=0.0, blue=1.0}
                            end
                        end,
  },
```
![output](https://github.com/genometools/genometools/assets/27732/3c108a22-b276-4ad4-a9df-1c364f1e745d)

**Comment by paristzou** [comment]
That's fascinating. Thank you very much for the help.
