### ISSUE TITLE
-Werror is for CI + developer only

### ISSUE THREAD

**Issue by dschwoerer** [genometools/genometools#1024]
## Problem description
`-Werror` is enabled by default. You shouldn't cause issues for users that use a compiler that detects other things than you.
They are warnings by default for a reason, and while I sympathize that you try to have a code without warnings, it is unreasonable to expect compilers not to add new warnings.

## Exact command line call triggering the problem
```
make
```

## Example minimal input triggering the problem
Running any fedora, even the oldest supported one, has a to recent compiler to not detect potential errors in the code.

## What GenomeTools version are you reporting an issue for (as output by `gt -version`)?
v1.6.2

## Did you compile GenomeTools from source? If so, please state the `make` parameters used.
N/A

## What operating system (e.g. Ubuntu, Mac OS X), OS version (e.g. 15.10, 10.11) and platform (e.g. x86_64) are you using?
Fedora 36 on x86_64
gcc (GCC) 12.3.1 20230508 (Red Hat 12.3.1-1)

**Comment by standage** [comment]
It's been a while since I've contributed anything substantial, so take this for what it's worth, but...

I'm sympathetic. I think when GenomeTools was under more active development, we could expect the code to keep up with compiler updates. Now that the the project has shifted primarily to maintenance and bugfixes, I'm not sure that `-Werror` makes sense as the default anymore. Maybe it's time to make it an opt-in feature rather than an opt-out feature?

**Comment by satta** [comment]
I usually try to keep up with (at least GCC) compiler checks to get things to build on Debian whenever they upgrade their default toolchain. But I agree that might not be well representative of the world out there, expecially Fedora ;)

Note that there is always the `errorcheck=no` Make option that disables `-Werror`. Making it opt-in is fine for me too, for those that really want to know these kinds of things.
Any comments from the rest of the development team?

**Comment by stefan-kurtz** [comment]
I agree that -Werror should not be the default, i.e. opt-in would be the way to go.

**Comment by satta** [comment]
Implemented in #1026
