### ISSUE TITLE
Build time issue with GenomeTools 1.5.9

### ISSUE THREAD

**Issue by yuwanziaaa** [genometools/genometools#1038]
Also why is your software depending on that old version? That build time issue (which I guess w as caused by using a newer compiler version) was likely fixed in a later version.

_Originally posted by @satta in https://github.com/genometools/genometools/issues/983#issuecomment-1971210807_

**Comment by yuwanziaaa** [comment]
Because geta(an annotation software) needs gt-1.5.9, and there is another error:

In file included from src/annotationsketch/canvas_cairo.c:34:
/mnt/sda/software/geta_dependencise/genometools-1.5.9/src/annotationsketch/graphics_cairo_api.h:21:10: fatal error: cairo.h: No such file or directory
   21 | #include <cairo.h>
      |          ^~~~~~~~~
compilation terminated.
make: *** [Makefile:811: obj/src/annotationsketch/canvas_cairo.o] Error 1

Additionaly, I'm curious that why "make errorcheck=no" can solve my first error?

**Comment by satta** [comment]
> Because geta(an annotation software) needs gt-1.5.9

The geta developers should look into supporting newer versions. TBH I doubt that much changed in GenomeTools in the meantime that would absolutely require the use of an old version.

> In file included from src/annotationsketch/canvas_cairo.c:34: /mnt/sda/software/geta_dependencise/genometools-1.5.9/src/annotationsketch/graphics_cairo_api.h:21:10: fatal error: cairo.h: No such file or directory 21 | #include <cairo.h> | ^~~~~~~~~ compilation terminated. make: *** [Makefile:811: obj/src/annotationsketch/canvas_cairo.o] Error 1

You need to either install the Cairo development headers and library (e.g. in Debian or Ubuntu install `libcairo2-dev` and `libpango1.0-dev`) or build with `errorcheck=no cairo=no` (after `make cleanup`). In the latter case you won't get AnnotationSketch support (`gt sketch`) but won't need to install the libraries.

> Additionaly, I'm curious that why "make errorcheck=no" can solve my first error?

Because it was not an actual error but a warning -- your compiler was complaining about something slightly problematic in the code that usually wouldn't be a problem, but we decided to make all warnings errors by default -- hence it presented itself to you as an error.
The `errorcheck=no` parameter just

**Comment by yuwanziaaa** [comment]
Thank you for your suggestion. I had a mistake that I got the software wrong. It's RepeatModeler require the  GenomeTools version 1.5.9. I don't know if the latest version is supported by RepeatModeler.If I do not use RepeatModeler,I would definitely install the latest gt version.

**Comment by yuwanziaaa** [comment]
Thank you for your help.
