### ISSUE TITLE
Suffixerator -tis option

### ISSUE THREAD

**Issue by andrewstephenmason** [genometools/genometools#185]
I'm using the gt suffixerator tool following the advice of the LTR Harvest user manual. So after database and indexname options, I'm specifying for options for: -tis -suf -lcp -des -ssp -sds -dna
This runs fine and gives file extensions: .des .esq .lcp .llv .md5 .prj .sds .ssp .suf
There is no .tis file - the user manual says this is necessary for LTR harvest to run. Sure enough, when I try it creates and out file and gff3 file that are empty. 
Any suggestions? I'm using gt 1.5.1
Thanks

**Comment by natassagioti** [comment]
Hi,
I am having the same issue i.e. no .tis file created despite not having a quota issue as Andrew did. I am running the 1.5.9 version on our institute computer clusters:
 $LTRhdir/gt suffixerator -version
/mnt/big/Tools/genometools-1.5.9/bin/gt suffixerator (GenomeTools) 1.5.9
Copyright (c) 2003-2016 G. Gremme, S. Steinbiss, S. Kurtz, and CONTRIBUTORS
Copyright (c) 2003-2016 Center for Bioinformatics, University of Hamburg
See LICENSE file or http://genometools.org/license.html for license details.
Used compiler: cc (Debian 6.3.0-18+deb9u1) 6.3.0 20170516
Compile flags:  -g -Wall -Wunused-parameter -pipe -fPIC -Wpointer-arith -Wno-unknown-pragmas -O3 -Werror

 Running file gives this (so I guess it is 64bit):
/mnt/big/Tools/genometools-1.5.9/bin/gt: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.32, BuildID[sha1]=1ea10234f977bf4e3164aa145c2fbc0b7938751e, not stripped

..which might not be relevant anyways because I am running it on a small genome (<35 Mbp)

I also tried deleting the index files and rerunning in a new directory, and I get the same problem. Files created: llv, lcp, prj, suf, ssp, esq, md5, sds, des. 
My command:
gt suffixerator -db $genomedir/mygenome.fa -indexname $genomedir/mygenome.fa -tis -suf -lcp -des -ssp -sds -dna -v
I am also attaching here  the output I got from running verbose in case it might help.
Last note, I discovered that the tis file was missing when troubleshooting an ltrdigest error :
ltrdigest: error: cannot open file "/home1/romanos/share/genomes/mygenome.fa.
[suffixerator.txt](https://github.com/genometools/genometools/files/4019275/suffixerator.txt)
ois": No such file or directory
after running:
ltrdigest -hmms $hmmdir/*.hmm -outfileprefix Trit_ltrdigest -encseq /home1/romanos/share/genomes/ mygenome.fa -matchdescstart < sorted_input_gff > Trit_ltrdigest_output_gff 

I am running out of ideas on how to move this forward, please help!
Thanks, 
Natassa

**Comment by satta** [comment]
AFAIK there is no longer a ` .tis` (transformed input sequence) file, this is now the `.esq` (the encoded sequence). This is what the tools like LTRharvest use, together with the enhanced suffix array. The LTRharvest manual you have seems to be a bit outdated in this regard as it was probably written _before_ the introduction of the encoded sequence into the GenomeTools codebase.

The missing `.ois` (original input sequence) file can be explained by the missing `-lossless` switch

What exactly are you trying to do? To run LTRharvest and LTRdigest, it should be enough to do:
```
$ gt suffixerator -db 4_genomic_dmel_RELEASE3-1.FASTA.gz -indexname dmel4 -suf -lcp -des -ssp -sds -dna -lossless -v
$ gt ltrharvest -index dmel4 -seqids yes -md5 yes -tabout no | gt gff3 -sort -retainids -tidy > LTRharvest.gff3
$ gt ltrdigest -hmms ../GyDB_collection/profiles/*hmm -encseq dmel4 -v < LTRharvest.gff3 > LTRdigest.gff3
```
(example run on _D. melanogaster_ chromosome 4 for brevity, but you get the idea)

**Comment by natassagioti** [comment]
Many thanks!
I am indeed based on outdated manuals, but I could not find any updated info. I am running LTRharvest and digest, and your advise on the -lossless fixed the issue!
Natassa
