### ISSUE TITLE
gt_readjoiner_assembly_runner bug

### ISSUE THREAD

**Issue by yifangt** [genometools/genometools#396]
Hello, I met this problem with gtgt_readjoiner_assembly_runner, which might be a bug.
My command is:

```
$ gt readjoiner assembly  -readset test.fasta -l 60
# gt readjoiner assembly (version 1.2)
Assertion failed: (reads != NULL), function gt_readjoiner_assembly_runner, file src/tools/gt_readjoiner_assembly.c, line 510.
This is a bug, please report it at https://github.com/genometools/genometools/issues.
```

I appreciate if you could let me know there is anything that I may have missed.

**Comment by deprekate** [comment]
How do I limit the contig to be the best contig?

i.e. there should only be one contig generated from the above input file "test.fasta"; since you should not assign a single read (in this case "test2" is used to build both "contig_0" and "contig_1") to multiple contigs.

________________________________________
The correct contig output for the above test.fasta should be >contig_0 and the singlet sequence >2
________________________________________


Pseudo Alignment

    >contig_0     acgtacgtacgtagcatagcgatatgactta
    >1            acgtacgtacgtagc
    >test2                 cgtagcatagcgatatgactta


    >contig_1     gatcgatcgtagcatagcgatatgactta
    >2 (rev)      gatcgatcgt
    >test2               cgtagcatagcgatatgactta

**Comment by Garonenur** [comment]
Hi @deprekate,

maybe it would be better to open a new issue for this?
