### ISSUE TITLE
seqorder: Sort sequences lexicographically by FASTA ID (feature request)

### ISSUE THREAD

**Issue by sjackman** [genometools/genometools#632]
I'd like to sort the sequences lexicographically be FASTA ID rather than by sequence. I actually found the latter behaviour a bit surprising, although I see that it could be useful. The `-sort` documentation could be improved by changing `sort sequences lexicographically` to `sort sequences lexicographically by sequence`.

http://genometools.org/tools/gt_seqorder.html

**Comment by sjackman** [comment]
I'd like three options:
1. Sort by FASTA ID lexicographically
2. Sort by FASTA ID numerically
3. Sort by sequence lexicographically

I noticed that the output is all lower case. Is it possible to preserve case? Lower case is often used to mask repeat sequence.

**Comment by sjackman** [comment]
Simple shell script to accomplish the same:
```sh
seqtk seq - |paste - - |sort |gsed 's/\t/\n/'
```

**Comment by Garonenur** [comment]
The sorting by sequence makes much more sense from an informatics view: many algorithms perform better if the sequences are sorted lexicographically. (Compression being one of them) The IDs of the sequences are meta information only needed for downstream interpretation.

That said, I think to add an option to seqorder, that uses the IDs is not a bad idea :) but I would leave the documentation as is. Because the focus should lie on the sequence, not its ID.

**Comment by sjackman** [comment]
`samtools sort` and most every other tool I can think of sorts by ID. I understand your justification, but it's not typical.

**Comment by sjackman** [comment]
Thanks, Sascha!
