### ISSUE TITLE
Suffixerator says my sequences are empty ?

### ISSUE THREAD

**Issue by FathisMunk** [genometools/genometools#634]
Hello,

I am trying to get LTRHarvest and LTRDigest to work on my computer and I figured I'd try an easy small scale test first just to see what the outputs actually look like and if I can manage it since I have pretty much no bio informatics background.

I chose a small file with 3 25kb locuses from the dog genome that I know to contain an almost complete provirus each. However every time I try to start suffixerator as described in the LTRHarvest manual, it tells me my sequence is empty.

My fasta sequences are in a text file ending in .fas as your exemple file does (even though I'm not sure the file extension is important) and follow the format : 

.>sequence_name
*sequence in caps A,T,G,C*
.>sequence2_name
*sequence2 in caps A,T,G,C*
etc...

(Without the . in front of the >, just put it there to avoid GitHub's formatting)

Why does suffixerator think my sequences are empty ?

Thanks in advance.

**Comment by satta** [comment]
Maybe your input file has DOS-like line terminators but you are using it on a Unix-like system (Linux, OS X)? If your file is `sequence.fasta`, you can use
```
file sequence.fasta  
```
to find out more about the format. If the output says something about CRLF line endings, you will need to convert it to a correct format using the `dos2unix` tool to make suffixerator read it properly.

**Comment by FathisMunk** [comment]
I'm using Mac OS X 10.8.5, this is my work computer and updating the OS would break a couple of the programs we are commonly using so I'm stuck with this OS for now. The text file was created on that same computer.

Using the file command tells me 
locus_Cf.fas: ASCII text, with CR line terminators

**Comment by satta** [comment]
Interesting. That could explain it -- with CR line endings only, the FASTA parser will treat the whole file as the first sequence header, as it will never recognize a new line being started. I am curious, how did you generate such a file? This style of line ending hasn't been very common since Mac OS 9!

You can use the `tr` command to convert the line endings with:
```
tr '\r' '\n'<  sequence.fasta > sequence.fixed.fasta
```
and then use the `sequence.fixed.fasta` file from then on.

Does this help?

**Comment by FathisMunk** [comment]
Welp, that seems to have fixed it thanks !

If I remember correctly that file was generated by SerialCloner 2.6.1 when I exported several .xdna files to generate a fasta file containing them all. I guess I will just copy and paste from now on to avoid that. I also checked a couple other fasta files generated by SerialCloner and it turns out all of the .txt have CR line terminators.

Anyways thanks a lot, I'd never have figured this out on my own that goes beyond my basic knowledge of file formats.

**Comment by satta** [comment]
This seems to be a peculiarity of SerialCloner output I guess. If it has been around since the classic Mac OS days then they probably just didn't adapt the output to Mac OS X.
Just use the command above to make sure the line endings are LF and not CR and you should be fine.
Happy to have been of help, closing this issue.
