### ISSUE TITLE
potential bug -tidy or -fixregionboundaries

### ISSUE THREAD

**Issue by gonzalezibeas** [genometools/genometools#636]
Hi, I am running a command with the option -fixregionboundaries to try to fix wrong phase CDS and I get an error that says "potential but, please report".

command:
gt gff3 -sort -fixregionboundaries scaffold399607.gff3 > sorted.gff

error:
Assertion failed: (!err || !gt_error_is_set(err)), function gt_node_stream_next, file src/extended/node_stream.c, line 89.
This is a bug, please report it.

Thank you.

**Comment by satta** [comment]
Thanks for reporting this! First of all, to fix CDS phases you need the `-tidy` option otherwise the parsing stops at the first problematic CDS. The `-fixregionboundaries` option is not necessary for that.

However, this should not cause an assertion to fail! Could you please let us know what GenomeTools version you are using? Also, could you probably make your input file `scaffold399607.gff3` available to us, or alternatively isolate a fraction of the GFF file triggering the problem?

Thanks, Sascha

**Comment by gonzalezibeas** [comment]
Hi,

thank you for the answer. I have realized that I am using version 1.5.1. I am trying to install version 1.5.6 in case this bug was previously fixed, for you to consider also. How can I attach a GFF file?. the application lets me only upload pictures. Tank you.

**Comment by gonzalezibeas** [comment]
Hi,

the problem is fixed in version 1.5.6, so you can delete the thread. sorry. thank you.

**Comment by satta** [comment]
Good to hear your problem is solved! Closing this issue then.
