### ISSUE TITLE
gt gff3 -checkids

### ISSUE THREAD

**Issue by agolicz** [genometools/genometools#696]
Hello,

I have a bit of a problem with gt gff3, I wanted to check if I have duplicate gene ids in my file, but the flag seems not to be working.

After gt gff3 -sort yes -retainids yes -checkids yes test.gff3 > gt.out.gff3

[gt.out.gff3.txt](https://github.com/genometools/genometools/files/42371/gt.out.gff3.txt)
[test.gff3.txt](https://github.com/genometools/genometools/files/42372/test.gff3.txt)

There is no warning about duplicate gene ids although they are present. The duplicate gene gets grouped with the first gene.  I tested v1.5.7 and v.1.5.4
Is that expected behavior? It seems counter-intuitive.

I also have a historical question. I was trying to re-run some analysis from 2012. Back then I used v.1.3.5 and I used to get warnings:
warning: feature ID "BOLE_PAN00005191.1:cds" not unique: changing to BOLE_PAN00005191.1:cds.1

But what I did not notice is that for some genes the ids got changed and for the others not.

So I ended up with a mosaic file which looked like this: 
[historical.mosaic.gff3.txt](https://github.com/genometools/genometools/files/42373/historical.mosaic.gff3.txt)
 
Any idea what could have caused that back then? It seems bizarre. It is important 
for my re-analysis as I am trying to understand if it was a strange gff3 file or unexpected 
program behavior. Again no errors.

Best wishes,
Agnieszka

**Comment by gordon** [comment]
It seems that you did copy&paste with your files, they do not contain any tabs anymore.

Concerning your first problem: That's probably due to the fact that we relaxed a check in commit 20efc5c7dc0d47fc5437cbab846c072ac4b00f75 to fix issue #153.
That means that your two genes are now considered as a multi-feature. The GFF3 specification says:

> ID
> Indicates the ID of the feature. IDs for each feature must be unique within the scope of the GFF file. In the case of discontinuous features (i.e. a single feature that exists over multiple genomic locations) the same ID may appear on multiple lines. All lines that share an ID collectively represent a single feature.

If the genes would be separated by a `###` line the parser would throw an error, but since they are not they are considered now a multi-feature. I agree that it is seems counter-intuitive in your case, but changing it back to the old behaviour would break cases like the one described in issue #153 which are within the specification. If the example file was concatenated by you, make sure you add `###` lines. If it was produced like that by the software you used you could file a bug report upstream.

Concerning your second problem: This might be related to the same code change as above or be due to some bugs we fixed in the meantime. Unfortunately, we cannot support old releases of GenomeTools. You could dig through old issues and commits yourself to figure out what changed. If you can produce an imput file which produces an error in the current version of GenomeTools we'll look into it, though. Sorry.

**Comment by agolicz** [comment]
Thanks very much for your reply. Sorry for the tabs, I was working on a windows machine and just c&p as an example. The problem with a lot of gff3 (gff3-like) files I work with is that they 
do not contain ### separating genes and they are often provided by third parties.

Would it be maybe possible to change the documentation/description of -checkids option.
The documentation says:
-checkids            make sure the ID attributes are unique within the scope of
                           each GFF3_file, as required by GFF3 specification

I may be confused but I understood 'scope of each GFF3_file' as the whole file not just entries between ###.
The documentation has not changed since v.1.3.x but the functionality of the flag did.
It may cause problems when people want to run the same pipeline, just update versions, they look at the documentation and it suggest functionality is the same.

Thanks again.

Best wishes,
Agnieszka

**Comment by gordon** [comment]
Good point, I'll change the documentation accordingly!

**Comment by gordon** [comment]
The new `gt gff3 -help` output would look like this:

> -checkids            make sure the ID attributes are unique within the scope of
>                     each GFF3_file, as required by GFF3 specification
>                    (memory consumption is proportional to the input file
>                     size(s)).
>                    If features with the same Parent attribute are not
>                    separated by a '###' line the GFF3 parser tries to treat
>                    them as a multi-line feature. This requires at least
>                    matching sequence IDs and types.

Do you think that is clearer?

**Comment by agolicz** [comment]
Yes. Looks good.

Best wishes,
Agnieszka
