### ISSUE TITLE
Consider supporting newer Lua versions

### ISSUE THREAD

**Issue by satta** [genometools/genometools#778]
Lua 5.1 is not really supported by upstream with 5.1.5 being the latest version (from 2012). We should find out what still keeps us from supporting a newer version, and make the necessary adjustments.
IIRC there were some incompatible API changes?

**Comment by gordon** [comment]
Lua 5.2 and 5.3 introduced incompatible changes and upgrading will require some changes to our code base. Last time I checked some of our Lua dependencies were also not compatible with newer versions (yet). Many projects seem to be stuck with Lua 5.1 due to this incompatible changes. I'm not against upgrading, but it will take considerable work.

**Comment by satta** [comment]
OK, understood -- thanks!
