### ISSUE TITLE
latex documentation math recognition

### ISSUE THREAD

**Issue by Garonenur** [genometools/genometools#826]
## Problem description
the lua docvisitor for latex recognizes some documentation as latex math and surrounds it by ```$```.

- [ ] ```$``` is tex, latex should use ```\(```
- [ ] sometimes numbers are next to symbols like ```>```, these should be included into the math environment
- [ ] if two math environments are next to each other, could those be combined?

**Comment by Garonenur** [comment]
I am not sure if the first point is as straight forward as it sounds. ```\(...\)``` is fragile and breaks if it is within other latex-elements as ```\section{...}``` for example.

**Comment by Garonenur** [comment]
- [ ] ```>=``` will be split up resulting in latexcode ```$>$=```, should be ```>=```

**Comment by satta** [comment]
Is there a specific reason for disallowing `$` (other than principle ;)) 
IIRC you might be able to make `\(` `\)` non-fragile using the `fixltx2e` package, it might help including this into the documentation source you are generating.

Otherwise I guess this would be some small changes to `codify()` (https://github.com/genometools/genometools/blob/master/gtdata/modules/gtdoclib/docvisitorlatex.lua#L56). Cool to look at it after 8 years, I didn't remember how much markup I supported in the first place!

**Comment by Garonenur** [comment]
seems like ```\(\)``` is not breaking anything. mostly it is used in "just" normal text, so it should be no problem. I have the other stuff covered, too. I think.
