### ISSUE TITLE
removing false positives

### ISSUE THREAD

**Issue by metzti** [genometools/genometools#881]
Hey there,

Is there a common way to remove false positives which are introduced by LTR-Harvest? I was following this protocol (http://weatherby.genetics.utah.edu/MAKER/wiki/index.php/Repeat_Library_Construction-Advanced) but it does not work for me as I get stuck at some point. 

kind regards

**Comment by satta** [comment]
Without looking at the protocol (sorry, no time), in general one could try augmenting the LTRharvest output with extra annotations using LTRdigest (`gt ltrdigest`) and then remove all initial candidates which do not have any extra PPT, PBS or pHMM protein matches inside (`gt select` + Lua).

**Comment by metzti** [comment]
Hey,

thanks for your kind help. So I did this, but encounter another problem, because the last step does not seem to work. I died gt select with the filter_protein_match.lua script but when I then want to get sequences with the  get_ltr_retrotransposon_seqs.pl  script I do not get any sequences out. 

I used: gt select  -rule_files path/to/file/filter_protein_match.lua -- /path/to/file/ltrdigestoutput > gt_select_output

and

perl -w /path/to/script/get_ltr_retrotransposon_seqs.pl /path/to/file/ltrharvestoutput.fasta /path/to/file/gt_select_output > gt_select_output.fasta

**Comment by satta** [comment]
Can you confirm that your `gt select` output contains any features?

**Comment by satta** [comment]
Hi Felipe,

I am not sure if I can help, the Perl script is not mine and I can only guess what might be the problem. One thing I can see from Avril's writeup on her blog is that the 

```
gt select -rule_files ~ss34/filters/filter_protein_match.lua -- < myspecies_ltrdigest_output_gff > mmyspecies_ltrdigest_output_gff2
```

step (step 3) is unlikely to work like this since `~ss34` is my home directory on Sanger's machines which will most likely not work on your system ;) You can get the filter_protein_match.lua here:
https://github.com/satta/filterama/blob/master/filter_protein_match.lua
(hopefully this is the one thet Avril used)

Also, where did you get the `get_ltr_retrotransposon_seqs.pl`? It's not part of the GenomeTools distribution and the path in step 4 in the blog mentions `~alc/Documents/000_50HG_Repeats/` which is also a path on Sanger machines. Unfortunately, I am no longer working there so I can't check...
Maybe it would help to get in touch with Avril? Otherwise, I might take a look with a sample genome if you could let me have the Perl script?

Cheers
Sascha

**Comment by faguil** [comment]
Hi Sascha,

Thanks for your reply. I have used the filter_protein_match.lua file that you suggested and the step 3 worked well. I am now stuck in getting the sequences using the  get_ltr_retrotransposon_seqs.pl script.

I got the Perl script from here: https://gist.github.com/avrilcoghlan/4037d6b8cca32eaf48b0 

I have pasted the script below: 

#!/usr/local/bin/perl

$fasta = $ARGV[0];
$gff = $ARGV[1];

# read in the gff file to find which sequences to take:
%TAKE = ();
$num_to_take = 0;
open(GFF,"$gff");
while(<GFF>)
{  
   $line = $_;
   chomp $line;
   if (substr($line,0,1) ne '#')
   {  
      # seq0    LTRharvest      LTR_retrotransposon     227145  239120  .       -       .       ID=LTR_retrotransposon1;Parent=repeat_region
1;ltr_similarity=98.06;seq_number=0
      # seq0    LTRharvest      LTR_retrotransposon     1847908 1862843 .       -       .       ID=LTR_retrotransposon2;Parent=repeat_region
2;ltr_similarity=87.74;seq_number=0
      # seq0    LTRharvest      LTR_retrotransposon     3847365 3852453 .       +       .       ID=LTR_retrotransposon3;Parent=repeat_region
3;ltr_similarity=96.35;seq_number=0
      @temp = split(/\t+/,$line);
      $seq = $temp[0]; # eg. seq0
      $feature = $temp[2];
      if ($feature eq 'LTR_retrotransposon')
      {  
         $start = $temp[3];
         $end = $temp[4];
         $seq = $seq."_".$start."_".$end;
         $TAKE{$seq} = 1;
         $num_to_take++;
      }
   }
}
close(GFF);

# read in the fasta file of sequences, and print out those we want to take:
$take = 0;
$num_found = 0;
open(FASTA,"$fasta");
while(<FASTA>)
{  
   $line = $_;
   chomp $line;
   if (substr($line,0,1) eq '>') # >chromosome:WBcel235:I:1:15072434:1 chromosome I (dbseq-nr 0) [65157,67865]
   {
      @temp = split(/\s+/,$line);
      $seqno = $temp[$#temp-1]; # eg. 0)
      chop($seqno); # eg. 0
      $pos = $temp[$#temp]; # eg. [65157,67865]
      $pos = substr($pos,1,length($pos)-2);
      @temp = split(/\,/,$pos);
      $start = $temp[0];
      $end = $temp[1];
      $seq = "seq".$seqno."_".$start."_".$end;
      if ($TAKE{$seq}) { $take = 1; $num_found++;} else { $take = 0;}
   }    
   if ($take == 1) { print "$line\n";}
}
close(FASTA);
if ($num_found != $num_to_take) { print STDERR "ERROR: num_found $num_found num_to_take $num_to_take\n"; exit;}
print STDERR "FINISHED\n";

I have been working using awk and sed, and I have extracted the sequences, but I am not 100% sure that I have done it properly. It would be nice to have your comments about the Perl script. The Avril's blog has been really useful.

Thanks in advance,

Cheers,

Felipe

**Comment by satta** [comment]
The Perl script makes quite a few assumptions about the format of the input sequences and annotations, for example that the sequence IDs are numbered like `seq0`, `seq1`, ... etc. This is a legacy format that was used at the time of the original LTRharvest paper but has long since been replaced by a GFF3 based handling. So if you have non-rewritten sequence IDs in LTRharvest/LTRdigest, then the script won't work.

Note that you can also get the sequences for each remaining element using GenomeTools only.  Here's a quick approach that I just tried from memory with a fly chromosome as an example:

```
# Get sequences
wget ftp://ftp.ensembl.org/pub/release-93/fasta/drosophila_melanogaster/dna/Drosophila_melanogaster.BDGP6.dna.chromosome.3R.fa.gz

# Create index
gt suffixerator -dna -db Drosophila_melanogaster.BDGP6.dna.chromosome.3R.fa.gz -lcp -ssp -suf -tis -des -lossless

# Find candidate elements
gt ltrharvest -index Drosophila_melanogaster.BDGP6.dna.chromosome.3R.fa.gz -tabout no -seqids -md5 > dmel6_3R.ltrh.gff3

# Quick check of results
gt stat dmel6_3R.ltrh.gff3

# Get profile HMMs
wget http://gydb.org/gydbModules/collection/collection/db/GyDB_collection.zip
unzip GyDB_collection.zip

# Annotate candidates with pHMM hits
gt -j 4 ltrdigest -hmms GyDB_collection/profiles/*hmm -encseq Drosophila_melanogaster.BDGP6.dna.chromosome.3R.fa.gz -matchdescstart < dmel6_3R.ltrh.gff3 > dmel6_3R.ltrd.gff3

# Get filter definition
wget https://raw.githubusercontent.com/satta/filterama/master/filter_protein_match.lua

# Filter out elements with no protein domain hits
gt select -rule_files filter_protein_match.lua < dmel6_3R.ltrd.gff3 > dmel6_3R.ltrd.filtered.gff3

# Quick check how many remain
gt stat dmel6_3R.ltrd.filtered.gff3

# Extract sequences for each elements
 gt extractfeat -type LTR_retrotransposon -encseq Drosophila_melanogaster.BDGP6.dna.chromosome.3R.fa.gz -matchdescstart < dmel6_3R.ltrd.filtered.gff3 > dmel6_3R.ltrd.sequences.fasta
```

This is a full working way from a genome sequence to a filtered set of annotations and single element sequences, with likely FPs removed. Hope that helps!

**Comment by bioinfo-Kacst** [comment]
Satta can i use this pipeline above for a eukaryotic denovo prediction, and classification annotation.  is the parameters written in ltrharvest and ltr digest paper would be suitable for mammal genome.

and can you explain more about the last step gt extractfeat?
