### ISSUE TITLE
Assertion failed when reading GFF

### ISSUE THREAD

**Issue by AlexWeinreb** [genometools/genometools#990]
## Problem description

When my input file contains the lines given in the minimal example, `gt` fails with this error:

Assertion failed: (elemidx >= q->front), function gt_queue_remove, file src/core/queue.c, line 135.

This may be similar to [that issue](https://github.com/genometools/genometools/issues/877) although the same solution doesn't seem to apply (here no feature appearing twice).

## Exact command line call triggering the problem

```
gt gff3 -tidy fail.gff3
```

## Example minimal input triggering the problem

[fail.gff3.txt](https://github.com/genometools/genometools/files/7204687/fail.gff3.txt)

(txt extension added for Github to accept upload)

## What GenomeTools version are you reporting an issue for (as output by `gt -version`)?

Tested both with the Debian packaged version and the latest 1.6 binary.
```
gt (GenomeTools) 1.5.10
[...]

Used compiler: cc (Debian 8.2.0-8) 8.2.0
Compile flags: -g -O2 -fdebug-prefix-map=.=. -fstack-protector-strong -Wformat -Werror=format-security -g -Wall -Wunused-parameter -pipe -fPIC -Wpointer-arith -Wno-unknown-pragmas -O3
```

Same error with
```
/opt/gt-1.6.2-Linux_x86_64-64bit-barebone/bin/gt (GenomeTools) 1.6.2
[...]

Used compiler: cc (Ubuntu/Linaro 4.6.3-1ubuntu5) 4.6.3
Compile flags:  -g -Wall -Wunused-parameter -pipe -fPIC -Wpointer-arith -Wno-unknown-pragmas -O3 -m32 -m64 -Wno-strict-overflow -Werror
```

## What operating system (e.g. Ubuntu, Mac OS X), OS version (e.g. 15.10, 10.11) and platform (e.g. x86_64) are you using?

Debian 4.19.194-3 (2021-07-18) x86_64 GNU/Linux

**Comment by satta** [comment]
Thanks! It's an interesting case of a connected component of features that are connected via shared `CDS` features:
```
##gff-version 3
III	rtracklayer	gene	9084306	9089386	.	-	.	ID=WBGene00008514;Name=mrpl-44
III	rtracklayer	gene	9086744	9089472	.	-	.	ID=WBGene00303021;Name=F02A9.10
III	rtracklayer	mRNA	9084306	9089386	.	-	.	Parent=WBGene00008514;ID=21579;Name=F02A9.4.2
III	rtracklayer	mRNA	9084310	9089375	.	-	.	Parent=WBGene00008514;ID=21580;Name=F02A9.4.1
III	rtracklayer	mRNA	9086744	9089375	.	-	.	Parent=WBGene00303021;ID=21581;Name=F02A9.10.1
III	rtracklayer	mRNA	9086744	9089472	.	-	.	Parent=WBGene00303021;ID=21582;Name=F02A9.10.2
III	rtracklayer	CDS	9089162	9089270	.	-	.	Parent=21579,21580,21581,21582;
III	rtracklayer	CDS	9089319	9089373	.	-	.	Parent=21579,21580,21581,21582;
```
![example](https://user-images.githubusercontent.com/27732/134223262-da2fae06-c7a2-43c6-9e71-8461a1dc8fcc.png)

So the parent nodes (`gene`s) should be attached to a pseudo node. However, since there are multiple ways to get to the parents (one via each `mRNA`, which are all parents of each `CDS`) the parser gets these roots redundantly multiple times from `find_roots()` and then, when trying to join the roots, tries to remove them too often from the `genome_nodes` queue, triggering the assertion. This looks lilke an uncommon case, but it should not break the parser though ;)

A solution would be to deduplicate the roots before joining them (#991), and indeed this fixed the issue:
```
$ bin/gt gff3 -tidy ~/Downloads/fail.gff3.txt
warning: seqid "III" on line 0 in file "generated" has not been previously introduced with a "##sequence-region" line, create such a line automatically
warning: CDS feature on line 9 in file "/home/satta/Downloads/fail.gff3.txt" has the wrong phase . -> correcting it to 0
warning: CDS feature on line 8 in file "/home/satta/Downloads/fail.gff3.txt" has the wrong phase . -> correcting it to 2
##gff-version 3
##sequence-region   III 9084306 9089472
III	rtracklayer	gene	9084306	9089386	.	-	.	ID=gene1;Name=mrpl-44
III	rtracklayer	mRNA	9084306	9089386	.	-	.	ID=mRNA1;Parent=gene1;Name=F02A9.4.2
III	rtracklayer	mRNA	9084310	9089375	.	-	.	ID=mRNA2;Parent=gene1;Name=F02A9.4.1
III	rtracklayer	gene	9086744	9089472	.	-	.	ID=gene2;Name=F02A9.10
III	rtracklayer	mRNA	9086744	9089375	.	-	.	ID=mRNA3;Parent=gene2;Name=F02A9.10.1
III	rtracklayer	mRNA	9086744	9089472	.	-	.	ID=mRNA4;Parent=gene2;Name=F02A9.10.2
III	rtracklayer	CDS	9089162	9089270	.	-	2	Parent=mRNA1,mRNA2,mRNA3,mRNA4
III	rtracklayer	CDS	9089319	9089373	.	-	0	Parent=mRNA1,mRNA2,mRNA3,mRNA4
###
```
I understand that the deduplication is an expensive operation, but it should only be triggered in expensive cases anyway (CCs with multiple roots). In any case, I would like to ask someone with deep knowledge of the parsing mechanism (@gordon?) to confirm that I did not miss any potentially problematic side effects.
Thanks!

**Comment by gordon** [comment]
Thanks for the fix @satta, I cannot quickly think of any problematic side effects.

**Comment by satta** [comment]
Great! @AlexWeinreb this should now be fixed in the current master, let me know if there are problems building the new version.

**Comment by AlexWeinreb** [comment]
It builds and solve the issue. Thank you!
